name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: odnowa-472602
  SERVICE_NAME: odnowa-app
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/402523735278/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'odnowa-app-sa@odnowa-472602.iam.gserviceaccount.com'

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --project=${{ env.PROJECT_ID }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --port 8080
