name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: [TWÓJ ID PROJEKTU] # Zmień na swój ID projektu Google Cloud
  SERVICE_NAME: [NAZWA TWOJEJ USŁUGI] # np. apdep1
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/[NUMER PROJEKTU]/locations/global/workloadIdentityPools/[NAZWA PULI]/providers/[NAZWA DOSTAWCY]'
          service_account: '[NAZWA KONTA USLUGI]@[ID PROJEKTU].iam.gserviceaccount.com'

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --project=${{ env.PROJECT_ID }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --port 8080
